import { Role } from "@prisma/client";
import {prisma} from "@/prisma/client";

export async function seedUsers() {
  console.log("Seeding Users...");

  // Clear old data
  await prisma.user.deleteMany();

  const users = await prisma.user.createMany({
    data: [
      {
        email: "alice@example.com",
        name: "Alice Johnson",
        password: "hashedpassword123",
        phone: "9876543210",
        college: "Jadavpur University",
        year: "3",
        branch: "CSE",
        role: Role.USER,
        referralCode: "REFALICE123",
        shirtSize: "M",
        teamIDs: [], // empty array since no teams yet
      },
      {
        email: "bob@example.com",
        name: "Bob Singh",
        password: "hashedpassword456",
        phone: "9876543211",
        college: "IIT Kharagpur",
        year: "2",
        branch: "ECE",
        role: Role.CAMPUS_AMBASSADOR,
        referralCode: "REFBOB456",
        shirtSize: "L",
        teamIDs: [],
      },
      {
        email: "carol@example.com",
        name: "Carol Das",
        password: "hashedpassword789",
        phone: "9876543212",
        college: "NIT Durgapur",
        year: "1",
        branch: "ME",
        role: Role.ADMIN,
        referralCode: "REFCAROL789",
        shirtSize: "S",
        teamIDs: [],
      },
      {
        email: "dan@example.com",
        name: "Dan Patel",
        password: "hashedpassword101",
        phone: "9876543213",
        college: "BITS Pilani",
        year: "4",
        branch: "EEE",
        role: Role.USER,
        referralCode: "REFDAN101",
        shirtSize: "XL",
        teamIDs: [],
      },
      {
        email: "emma@example.com",
        name: "Emma Roy",
        password: "hashedpassword202",
        phone: "9876543214",
        college: "VIT Vellore",
        year: "2",
        branch: "IT",
        role: Role.REFERRED_USER,
        referralCode: "REFEMMA202",
        shirtSize: "XS",
        teamIDs: [],
      },
      {
        email: "frank@example.com",
        name: "Frank Sen",
        password: "hashedpassword303",
        phone: "9876543215",
        college: "SRM University",
        year: "3",
        branch: "Civil",
        role: Role.USER,
        referralCode: "REFFRANK303",
        shirtSize: "XXL",
        teamIDs: [],
      },
      {
        email: "grace@example.com",
        name: "Grace Mukherjee",
        password: "hashedpassword404",
        phone: "9876543216",
        college: "Amity University",
        year: "1",
        branch: "Biotech",
        role: Role.USER,
        referralCode: "REFGRACE404",
        shirtSize: "L",
        teamIDs: [],
      },
      {
        email: "harry@example.com",
        name: "Harry Mehta",
        password: "hashedpassword505",
        phone: "9876543217",
        college: "Manipal University",
        year: "2",
        branch: "Aerospace",
        role: Role.CAMPUS_AMBASSADOR,
        referralCode: "REFHARRY505",
        shirtSize: "M",
        teamIDs: [],
      },
      {
        email: "irene@example.com",
        name: "Irene Sharma",
        password: "hashedpassword606",
        phone: "9876543218",
        college: "Delhi University",
        year: "4",
        branch: "Physics",
        role: Role.USER,
        referralCode: "REFIRENE606",
        shirtSize: "S",
        teamIDs: [],
      },
      {
        email: "jack@example.com",
        name: "Jack Verma",
        password: "hashedpassword707",
        phone: "9876543219",
        college: "IIT Bombay",
        year: "3",
        branch: "Chemical",
        role: Role.ADMIN,
        referralCode: "REFJACK707",
        shirtSize: "XL",
        teamIDs: [],
      },
    ],
  });

  console.log(`✅ ${users.count} users seeded.`);
}
